### ISSUE TITLE
error after installing

### ISSUE THREAD

**Issue by Frits1980** [CopeX/CopeX_VatFix#1]
When I copy the files into folder app/code/CopeX/VATFix and run bin/magento setup:di:compile it stops compiling at 14% and says: [ErrorException] Uninitialized string offset: 1

**Comment by roman204** [comment]
Thank you for reporting, can you  provide a exact Magento Version + PHP Version?

**Comment by roman204** [comment]
hmm I am now behind the 14% 
![image](https://cloud.githubusercontent.com/assets/584168/14426306/64472964-ffee-11e5-8f6e-dbdf2927a42d.png)

What is in your exception.log ?

**Comment by Frits1980** [comment]
WOW! quick reaction! PHP 5.5 magento 2.0.4.

my exception log shows this:
`[2016-04-07 09:27:07] main.CRITICAL: exception 'Exception' with message 'Notice: Undefined index: arguments in /data/web/magento2/vendor/magento/framework/ObjectManager/Config/Compiled.php on line 132' in /data/web/magento2/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /data/web/magento2/vendor/magento/framework/ObjectManager/Config/Compiled.php(132): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/data/web/magen...', 132, Array)
#1 /data/web/magento2/vendor/magento/framework/App/ObjectManagerFactory.php(153): Magento\Framework\ObjectManager\Config\Compiled->extend(Array)
#2 /data/web/magento2/pub/errors/processorFactory.php(24): Magento\Framework\App\ObjectManagerFactory->create(Array)
#3 /data/web/magento2/pub/errors/report.php(10): Magento\Framework\Error\ProcessorFactory->createProcessor()
#4 /data/web/magento2/vendor/magento/framework/App/Http.php(270): require('/data/web/magen...')
#5 /data/web/magento2/vendor/magento/framework/App/Http.php(140): Magento\Framework\App\Http->handleGenericReport(Object(Magento\Framework\App\Bootstrap), Object(UnexpectedValueException))
#6 /data/web/magento2/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(UnexpectedValueException))
#7 /data/web/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#8 {main} [] []`

**Comment by roman204** [comment]
And you enabled the module ?

**Comment by Frits1980** [comment]
The module works fine and is enabled when I just run setup:upgrade. But when I run setup:di:compile I keep getting the error. When I remove the module compiling goes flawless.

**Comment by roman204** [comment]
hmm this is weird... will check and report here...

**Comment by roman204** [comment]
Is your php-version above 5.5.22 ?

**Comment by Frits1980** [comment]
php -version gives me this: PHP 5.5.30-1+deb.sury.org~precise+1

**Comment by Frits1980** [comment]
By any chance, any news yet?

**Comment by roman204** [comment]
yes good point to try it again with a stable magento2 which allows installing without errors... will try it these days, please be patient.

**Comment by Frits1980** [comment]
WOW, just solved it. I revised all files and the only thing I could not explain was the registration.php file. I replaced it's content with the "default magento" content:
`<?php
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'CopeX_VATFix',
    __DIR__
);`
And now it works.

**Comment by roman204** [comment]
Thanks for sharing, will update it asap.

Beste Grüße
Roman Hutterer
CopeX GmbH

sent from my mobile device.
Am 13.05.2016 16:21 schrieb "Frits1980" notifications@github.com:

**Comment by roman204** [comment]
fixed with commit:  [https://github.com/CopeX/CopeX_VatFix/commit/d95a7776ba345f3df2487dc469b6d26c68a5f49d](https://github.com/CopeX/CopeX_VatFix/commit/d95a7776ba345f3df2487dc469b6d26c68a5f49d)
