### ISSUE TITLE
Travis failing because of missing PHPUnit_Framework_TestCase

### ISSUE THREAD

**Issue by jissereitsma** [CopeX/CopeX_VatFix#10]
Travis is failing to run unit tests, because the class `PHPUnit_Framework_TestCase` is missing. The reason for this again is that you are using the latest version of Magento (version 2.2) to run PHPUnit but this is version 6 (?) while Magento 2.1 ships with PHPUnit version 4 and which is required for the tests. I'm working on a simple PR to copy the code from 2.1, instead of the latest GitHub source.

**Comment by roman204** [comment]
try to handle it via matrix in travis
