### ISSUE TITLE
Magento 2.2.6 checkout fails

### ISSUE THREAD

**Issue by JannMulton** [CopeX/CopeX_VatFix#12]
Hi

If new user reach to checkout where user doen't have any addresss assigned yet, the code fails in checkout.
If it cannot verify the code and add error message
       if (!empty($vatNumber) && !is_numeric($countryCodeFromVAT) && $countryCode != $countryCodeFromVAT) {
            $this->addErrorMessage(__('Your selected country does not match the countrycode in VAT.'));
            return [];
        }

error message not visible and function return empty array
 return [];

which causing parent function Magento\Customer\Model\Vat::checkVatNumber(), to fail

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Magento\Customer\Model\Vat::checkVatNumber(), 0 passed in htdocs/vendor/magento/framework/Interception/Interceptor.php on line 58 
and at least 2 expected in htdocs/vendor/magento/module-customer/Model/Vat.php:162 Stack trace: #0 htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\Vat->checkVatNumber() 
#1 htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\Vat\Interceptor->___callParent('checkVatNumber', Array) 
#2 htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\Vat\Interceptor->Magento\Framework\Interception\{closure}('EE', 'FI12345678', 'EE', '12345678') 
#3 /data01/virt71753/domeenid/www.multon. in htdocs/vendor/magento/module-customer/Model/Vat.php on line 162
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/922857370192"}]}}

**Comment by pointia** [comment]
Thanks for your issue.

We updated the plugin so it doesn't return an empty array.

Nontheless your problem is that your country is EE (Estonia) but your VAT is from Finland (FI12345678) which is not correct.
