### ISSUE TITLE
CopeX 1.0.9 Magento 2.4 compatibility

### ISSUE THREAD

**Issue by fkrieg** [CopeX/CopeX_VatFix#14]
We have a Magento 2.4.3-p1 installation running under php 7.4.27, VatFix installed via composer.  The module is installed and active but does not produce any output in the debug. Are there any known compatibility issues with Magento 2.4.3?

**Comment by pointia** [comment]
As far as I know the module is not needed anymore since Magento 2.3.1

**Comment by fkrieg** [comment]
Sorry for the late response - after having checked this issues it seems not to be needed anymore.
