### ISSUE TITLE
Error after registration

### ISSUE THREAD

**Issue by Tristan-N** [CopeX/CopeX_VatFix#3]
Installed module, registered new account and this error occured. 

![schermafbeelding 2016-09-15 om 15 34 05](https://cloud.githubusercontent.com/assets/19165453/18551708/ee75e814-7b59-11e6-814f-ccb878f0c283.png)

**Comment by roman204** [comment]
Thanks for your Message the error seems to come from the file 
vendor/magento/module-customer/view/frontend/templates/address/edit.phtml on line 66.
There should be:
    <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
Please look where the $isBTW comes from.
I cant find any property named "isBTW" in Magento2 Core.

This is a Plugin which executes code before the original method checkVatNumber in Magento\Customer\Model\Vat, it does not rewrite any Class. I doubt the error comes form this plugin.

**Comment by Tristan-N** [comment]
Wow. Thanks.

I feel a bit ashamed. What happend? I translated something hardcoded (
like echo __('BTW-nummer’)) but it also changed isVatAttributeVisible to is
BTW-nummerAttributeVisible. Error solved. Very stupid.

I doubt it was me that changed this, because it’s core code. But thanks a
lot for your sharp view.
