### ISSUE TITLE
Error while running di:compile

### ISSUE THREAD

**Issue by paales** [CopeX/CopeX_VatFix#4]
```
[Exception] 
Notice: Uninitialized string offset: 1 in /data/web/staging/setup/src/Magen 
to/Setup/Module/Di/Code/Reader/FileScanner.php on line 322 
```

**Comment by paales** [comment]
If I remove the module, everything works as expected. Experiencing this issue on Magento 2.1.2.

**Comment by roman204** [comment]
Hy,

there was an other issue which i think is the same.
Link: [https://github.com/CopeX/CopeX_VatFix/issues/1](https://github.com/CopeX/CopeX_VatFix/issues/1)

Which version of our module was used?

**Comment by paales** [comment]
I ran `composer require copex/vatfix`, so I guess that's `0.0.1` as mentioned in the `composer.json` file.

**Comment by roman204** [comment]
thx @paales for that hint...(shame on me :-1: ) raised it and made new version 1.0.3.
now the latest version should be installed.

**Comment by roman204** [comment]
@paales does it work now?
