### ISSUE TITLE
Call to undefined method getCountryCodeFromVAT

### ISSUE THREAD

**Issue by niclashoyer** [CopeX/CopeX_VatFix#5]
The following error gets reported upon saving with a valid VatID:

```
PHP message: PHP Fatal error:  Call to undefined method CopeX\VATFix\Helper\Data::getCountryCodeFromVAT() in /var/www/magento2/vendor/copex/vatfix/Plugin/UidPlugin.php on line 45
```

It seems the `getCountryCodeFromVAT` is missing from the [helper](https://github.com/CopeX/CopeX_VatFix/blob/master/Helper/Data.php).

**Comment by roman204** [comment]
thanks for reporting, added missing method in 9c33d81b5d5f9a0402ee1fa324e3be40ea799573
