### ISSUE TITLE
Missing attributes in di.xml

### ISSUE THREAD

**Issue by Frits1980** [CopeX/CopeX_VatFix#6]
di.xml is starting with: `<config>`

this should be:
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">`

**Comment by roman204** [comment]
thanks for reporting, fixed it in 70962c2f30a86e9eabd840b152abd80a34c969c8
